const streamerDares = [
    {
        title: "Pack 1 - Easy",
        color: "bg-green",
        dares: [
            "End every sentence with 'Trust me' for 2 minutes (Be dramatic).",
            "Talk without saying 'I' for the next round.",
            "Pretend to be an airline pilot.",
            "Pretend to be an airline pilot until you win.",
            "Talk like a news anchor for 2 minutes.",
            "Reply to chat with emojis (Be dramatic).",
            "Give a passionate review of your mousepad for 2 minutes.",
            "End every sentence with 'Trust me'.",
            "Do a dramatic sigh every time you miss for the next round.",
            "Reply to chat with emojis for 10 minutes (Be dramatic).",
            "Do a dramatic sigh every time you miss for 5 minutes.",
            "Commentate on your own gameplay like an esports caster for 30 seconds (No cheating!).",
            "Compliment every new viewer.",
            "Commentate on your own gameplay like an esports caster.",
            "Refer to yourself in the third person for 3 minutes (Make it convincing).",
            "Read every message in a dramatic voice.",
            "Only whisper for 5 minutes.",
            "Pretend your keyboard is broken until you win (Make it convincing).",
            "Refer to yourself in the third person.",
            "Sing your in-game callouts (Give it 100%).",
            "Talk like a pirate (Be dramatic).",
            "Pretend you are hosting a cooking show (Make it convincing).",
            "Reply to chat with emojis (Give it 100%).",
            "Commentate on your own gameplay like an esports caster for the next round.",
            "Act like you are casting a magic spell for 3 minutes.",
            "Talk like a pirate until you win.",
            "Talk like a news anchor for the next round.",
            "Do a dramatic sigh every time you miss.",
            "Talk without saying 'I'.",
            "Use only one hand for 3 minutes (Give it 100%).",
            "Do a staring contest with the camera.",
            "Only whisper for 3 minutes (Chat watches closely).",
            "Talk like a news anchor for 10 minutes (Be dramatic).",
            "Only use your non-dominant hand for the mouse (Be dramatic).",
            "Use only one hand for 5 minutes.",
            "End every sentence with 'Trust me' for 5 minutes.",
            "Do a dramatic sigh every time you miss for 3 minutes.",
            "Give random shoutouts to chatters for 30 seconds.",
            "Read your last text message until you win.",
            "Pretend you're doing a makeup tutorial.",
            "Only whisper.",
            "Reply to chat with emojis.",
            "Hum your favorite song.",
            "Pretend your keyboard is broken for 10 minutes.",
            "Only use your non-dominant hand for the mouse for 30 seconds (Make it convincing).",
            "Compliment every new viewer (Be dramatic).",
            "Talk like a news anchor.",
            "Reply to chat with emojis until you win (Make it convincing).",
            "Pretend you are hosting a cooking show for 3 minutes (No cheating!).",
            "End every sentence with 'Trust me' for 1 minute.",
            "Pretend you are hosting a cooking show for 5 minutes (Give it 100%).",
            "Pretend you are hosting a cooking show for 10 minutes.",
            "Compliment every new viewer for 5 minutes.",
            "Commentate on your own gameplay like an esports caster for 2 minutes.",
            "Speak like a movie trailer narrator for 3 minutes.",
            "Read every message in a dramatic voice for 30 seconds (Chat watches closely).",
            "Compliment every new viewer until you win.",
            "Pretend you are hosting a cooking show for 5 minutes.",
            "Give random shoutouts to chatters.",
            "Give a passionate review of your mousepad for 1 minute.",
            "Pretend your keyboard is broken.",
            "Talk without saying 'I' for 10 minutes.",
            "Speak like a movie trailer narrator for 5 minutes (Give it 100%).",
            "Pretend you're doing a makeup tutorial for 1 minute.",
            "Sing your in-game callouts (No cheating!).",
            "Do a staring contest with the camera (Give it 100%).",
            "Pretend you are hosting a cooking show.",
            "Act surprised by everything that happens in the game for 2 minutes (Chat watches closely).",
            "Speak like a movie trailer narrator.",
            "End every sentence with 'Trust me' for 30 seconds.",
            "Do a dramatic sigh every time you miss for 30 seconds.",
            "Sing your in-game callouts for 10 minutes.",
            "Read your last text message for 30 seconds.",
            "Compliment every new viewer for 10 minutes (Be dramatic).",
            "Only use your non-dominant hand for the mouse for 10 minutes.",
            "Give random shoutouts to chatters for 5 minutes.",
            "Pretend to be an airline pilot (Give it 100%).",
            "Reply to chat with emojis for 5 minutes.",
            "Do a staring contest with the camera for 5 minutes.",
            "Act surprised by everything that happens in the game.",
            "Pretend to be an airline pilot until you win (No cheating!).",
            "Give a passionate review of your mousepad for 3 minutes.",
            "Act like you are casting a magic spell for the next round (Give it 100%).",
            "Use only one hand.",
            "Sing your in-game callouts.",
            "Talk without saying 'I' until you win.",
            "Sing your in-game callouts for 30 seconds (Give it 100%).",
            "Speak like a movie trailer narrator for 5 minutes.",
            "Only use your non-dominant hand for the mouse until you win.",
            "Sing your in-game callouts for 1 minute.",
            "Only whisper (Chat watches closely).",
            "Sing your in-game callouts for 1 minute (Make it convincing).",
            "Act surprised by everything that happens in the game for 30 seconds.",
            "Only use your non-dominant hand for the mouse.",
            "Speak like a movie trailer narrator for 1 minute.",
            "Hum your favorite song for 10 minutes.",
            "Read your last text message.",
            "Pretend your keyboard is broken for 1 minute.",
            "Commentate on your own gameplay like an esports caster (Give it 100%).",
            "Only use your non-dominant hand for the mouse for 5 minutes (Chat watches closely)."
        ]
    },
    {
        title: "Pack 2 - Medium",
        color: "bg-blue",
        dares: [
            "Pretend you are terrified of the game for 30 seconds (No cheating!).",
            "Pretend you are terrified of the game for 1 minute.",
            "Wear your headset backwards for 5 minutes.",
            "Hold your breath during gunfights.",
            "Pretend you are terrified of the game.",
            "Play with inverted controls until you win.",
            "Talk in slow motion for 5 minutes.",
            "Talk like a surfer dude for the next round.",
            "Fake an interview with yourself.",
            "Sing every answer (Give it 100%).",
            "Do an evil laugh when you score for 3 minutes.",
            "Pretend you are a secret agent for 30 seconds.",
            "Talk like a surfer dude for 1 minute.",
            "Pretend you are a medieval knight until you win (Give it 100%).",
            "Answer a trivia question before reloading.",
            "Sing every answer for the next round (Chat watches closely).",
            "Let chat pick your next weapon for the next round (Be dramatic).",
            "Pretend you are in a library.",
            "Wear a funny hat (Make it convincing).",
            "Play with inverted controls (Make it convincing).",
            "Sing every answer for 30 seconds.",
            "Pretend you are a secret agent for the next round.",
            "Act like a robot.",
            "Answer a trivia question before reloading for the next round.",
            "Sing every answer for 5 minutes.",
            "Let chat pick a word you must say (Make it convincing).",
            "Pretend to be an angry chef.",
            "Narrate everything you're doing.",
            "Let chat pick your next weapon.",
            "Pretend you are terrified of the game for 2 minutes.",
            "Play with inverted controls for 30 seconds (Make it convincing).",
            "Use a fake accent for 10 minutes.",
            "Play with inverted controls for the next round.",
            "Act like a robot for 30 seconds.",
            "Pretend you are in a library for 3 minutes.",
            "Explain strategy using food metaphors (Chat watches closely).",
            "Give your weapon a name for 5 minutes.",
            "Talk like a surfer dude (No cheating!).",
            "Narrate your game like an anime for 10 minutes.",
            "Act like a robot for 10 minutes.",
            "Talk like a surfer dude (Be dramatic).",
            "Use a fake accent (Give it 100%).",
            "Pretend you are in a library (Give it 100%).",
            "Pretend to be an angry chef (Chat watches closely).",
            "Explain the game to a 5-year-old for 10 minutes.",
            "Use a fake accent.",
            "Narrate your game like an anime for 30 seconds.",
            "Fake an interview with yourself for 2 minutes.",
            "Hold your breath during gunfights (Make it convincing).",
            "Give your weapon a name for 3 minutes (Chat watches closely).",
            "Talk like a surfer dude for 30 seconds.",
            "Explain the game to a 5-year-old until you win.",
            "Talk in slow motion for 10 minutes.",
            "Act like you are completely out of breath until you win.",
            "Pretend you are in a library for 30 seconds.",
            "Narrate your game like an anime until you win.",
            "Talk like a surfer dude.",
            "Wear a funny hat.",
            "Narrate your game like an anime for 5 minutes (No cheating!).",
            "Let chat pick your next weapon until you win.",
            "Answer a trivia question before reloading for 30 seconds (Chat watches closely).",
            "Give your weapon a name.",
            "Pretend you are terrified of the game (Make it convincing).",
            "Play with inverted controls for 3 minutes.",
            "Narrate your game like an anime for 3 minutes (Give it 100%).",
            "Act like you are completely out of breath (Make it convincing).",
            "Let chat pick your next weapon for 1 minute (Make it convincing).",
            "Sing every answer.",
            "Explain the game to a 5-year-old (No cheating!).",
            "Let chat pick your next weapon (Make it convincing).",
            "Talk in slow motion (No cheating!).",
            "Do an evil laugh when you score.",
            "Pretend you are a medieval knight for 2 minutes.",
            "Give your weapon a name for the next round.",
            "Answer a trivia question before reloading (Be dramatic).",
            "Do an evil laugh when you score for 1 minute.",
            "Narrate your game like an anime for 1 minute.",
            "Explain the game to a 5-year-old.",
            "Act like a robot for 1 minute (Give it 100%).",
            "Pretend you are a secret agent (Give it 100%).",
            "Wear your headset backwards.",
            "Let chat pick a word you must say until you win (Be dramatic).",
            "Talk in slow motion until you win (Give it 100%).",
            "Let chat pick a word you must say for 10 minutes (Give it 100%).",
            "Fake an interview with yourself for 10 minutes (Give it 100%).",
            "Narrate everything you're doing (Chat watches closely).",
            "Narrate everything you're doing for 3 minutes.",
            "Act like you are completely out of breath.",
            "Pretend you are terrified of the game for 5 minutes (Give it 100%).",
            "Use a fake accent (No cheating!).",
            "Give your weapon a name for 10 minutes (Be dramatic).",
            "Pretend you are in a library for 3 minutes (Be dramatic).",
            "Pretend you are a medieval knight.",
            "Narrate your game like an anime (No cheating!).",
            "Explain strategy using food metaphors.",
            "Play with inverted controls.",
            "Act like a robot for 2 minutes.",
            "Answer a trivia question before reloading until you win.",
            "Pretend you are a secret agent.",
            "Explain strategy using food metaphors for 3 minutes."
        ]
    },
    {
        title: "Pack 3 - Hard",
        color: "bg-yellow",
        dares: [
            "Do 5 sit-ups per loss for the next round.",
            "No jumping or sprinting for 5 minutes.",
            "Speak in a monotone voice.",
            "Thank a random object when you win for 1 minute (Give it 100%).",
            "Thank your chair after every round for 5 minutes (Make it convincing).",
            "Let chat pick background music.",
            "Let chat rename your stream (Give it 100%).",
            "Drop your weapon for 3 minutes.",
            "Every death = 5 pushups for 10 minutes.",
            "Only use your pistol (Make it convincing).",
            "Let chat rename your stream for 5 minutes.",
            "Do 10 jumping jacks for 10 minutes.",
            "Drop your weapon (Be dramatic).",
            "Let chat write a tweet for you for 30 seconds.",
            "Play with monitor tilted.",
            "Pretend to be a telemarketer for 3 minutes.",
            "Let chat mute your mic randomly for 10 minutes.",
            "Let chat write a tweet for you for 5 minutes (Chat watches closely).",
            "No speaking English (No cheating!).",
            "Stream standing up.",
            "No healing items for one game.",
            "Thank a random object when you win for 1 minute.",
            "Every win = victory dance (Chat watches closely).",
            "Only communicate with sound effects for 30 seconds.",
            "Pretend to be a telemarketer for the next round (Be dramatic).",
            "Every win = victory dance for 3 minutes.",
            "Let chat mute your mic randomly (Chat watches closely).",
            "Speak in a monotone voice until you win.",
            "No jumping or sprinting.",
            "Drop your weapon for the next round.",
            "Pretend to be a telemarketer for 10 minutes.",
            "Every death = 5 pushups for 1 minute.",
            "Drop your weapon for 1 minute.",
            "Drop your weapon for the next round (No cheating!).",
            "Let chat write a tweet for you.",
            "Speak in a monotone voice for the next round.",
            "Only use your pistol for 30 seconds (No cheating!).",
            "Let chat pick background music for 2 minutes (Chat watches closely).",
            "Every win = victory dance for 5 minutes.",
            "Every death = 5 pushups.",
            "Thank a random object when you win.",
            "Thank your chair after every round for 5 minutes.",
            "Apologize to every enemy you shoot for 3 minutes.",
            "No speaking English (Be dramatic).",
            "Speak in a monotone voice (Be dramatic).",
            "Pretend you are crying.",
            "Act like the game is a horror movie.",
            "Only communicate with sound effects for 10 minutes.",
            "Stream standing up for 30 seconds (Make it convincing).",
            "Thank your chair after every round (Chat watches closely).",
            "Apologize to every enemy you shoot.",
            "Apologize to every enemy you shoot for the next round.",
            "Do 5 sit-ups per loss (Give it 100%).",
            "Speak in a monotone voice for 5 minutes (No cheating!).",
            "Do 10 jumping jacks for 1 minute.",
            "No jumping or sprinting (No cheating!).",
            "Every win = victory dance for 2 minutes (Give it 100%).",
            "Thank a random object when you win for 3 minutes.",
            "Apologize to every enemy you shoot for 5 minutes.",
            "No laughing for 3 minutes (Chat watches closely).",
            "Every death = 5 pushups (No cheating!).",
            "Thank a random object when you win for 30 seconds.",
            "Let chat rename your stream for 3 minutes.",
            "Drop your weapon for 2 minutes.",
            "Let chat pick background music for 10 minutes.",
            "Pretend to be a telemarketer for 5 minutes.",
            "Thank a random object when you win (No cheating!).",
            "No speaking English for 2 minutes (Give it 100%).",
            "Apologize to every enemy you shoot for 1 minute (Give it 100%).",
            "Let chat mute your mic randomly (Be dramatic).",
            "No healing items for one game until you win.",
            "Do 10 jumping jacks.",
            "Pretend to be a telemarketer.",
            "Do 5 sit-ups per loss.",
            "Stream standing up (No cheating!).",
            "Thank a random object when you win for 10 minutes.",
            "Only use your pistol until you win.",
            "Pretend to be a telemarketer for 1 minute.",
            "Let chat rename your stream for 2 minutes.",
            "No speaking English for 1 minute (Make it convincing).",
            "No speaking English for 2 minutes.",
            "Do 5 sit-ups per loss for 10 minutes.",
            "Only use your pistol.",
            "Let chat mute your mic randomly.",
            "Let chat write a tweet for you (Chat watches closely).",
            "Do 5 sit-ups per loss for 5 minutes.",
            "Only communicate with sound effects.",
            "Do 10 jumping jacks for 3 minutes.",
            "No healing items for one game for the next round.",
            "Drop your weapon for 5 minutes.",
            "Only look at the ceiling for 30 seconds (Be dramatic).",
            "Let chat mute your mic randomly (Give it 100%).",
            "Stream standing up for 10 minutes (Be dramatic).",
            "Drop your weapon for 10 minutes.",
            "Apologize to every enemy you shoot until you win (Be dramatic).",
            "No speaking English for 2 minutes (Make it convincing).",
            "No laughing.",
            "Do 10 jumping jacks for the next round (Give it 100%).",
            "Let chat write a tweet for you for 1 minute (Chat watches closely).",
            "Let chat rename your stream."
        ]
    },
    {
        title: "Pack 4 - Chaos",
        color: "bg-green",
        dares: [
            "Randomly clap for the next round.",
            "Act in love with the enemy (Make it convincing).",
            "Speak like Shakespeare.",
            "Act like a grumpy old man for 1 minute.",
            "Sing the alphabet backwards (No cheating!).",
            "Speak only in haikus (Give it 100%).",
            "Roast yourself for 1 minute.",
            "Change game language for 3 minutes (Chat watches closely).",
            "Spin in chair 3 times.",
            "Sing a pop song chorus.",
            "Bark like a dog when you see an enemy.",
            "Roast yourself (Be dramatic).",
            "Narrate like a nature documentary until you win.",
            "Randomly clap for 30 seconds.",
            "Change game language (Be dramatic).",
            "Yell 'Parkour!'.",
            "Act in love with the enemy for 1 minute.",
            "Roast yourself (Make it convincing).",
            "Say 'Skill issue' for 3 minutes.",
            "Bark like a dog when you see an enemy until you win.",
            "Change game language for 1 minute.",
            "Speak like Shakespeare for 1 minute.",
            "Change game language for 1 minute (Make it convincing).",
            "Act like a grumpy old man for 1 minute (No cheating!).",
            "Act highly suspicious.",
            "Compliment opponents (Give it 100%).",
            "Pretend you're lagging.",
            "Max sensitivity.",
            "Act like a grumpy old man until you win (No cheating!).",
            "Sing the alphabet backwards for 5 minutes.",
            "Act in love with the enemy until you win.",
            "Meow every time you reload (Give it 100%).",
            "Call yourself 'The Legend' (Give it 100%).",
            "Meow every time you reload for 5 minutes (No cheating!).",
            "Pretend you forgot how to play for the next round.",
            "Roast yourself for 1 minute (Make it convincing).",
            "Roast yourself.",
            "Bark like a dog when you see an enemy for the next round (Make it convincing).",
            "Act highly suspicious for 2 minutes.",
            "Say 'Skill issue' for the next round (Be dramatic).",
            "Act like a grumpy old man.",
            "Yell 'Parkour!' for 30 seconds (Be dramatic).",
            "Sing the alphabet backwards for 30 seconds.",
            "Say 'Skill issue'.",
            "Sing the alphabet backwards for the next round.",
            "Say 'Skill issue' for 5 minutes.",
            "Speak only in haikus.",
            "Compliment opponents for 3 minutes (Chat watches closely).",
            "Act in love with the enemy (Be dramatic).",
            "Compliment opponents.",
            "Let chat decide sensitivity.",
            "Change game language for 2 minutes.",
            "Max sensitivity for 30 seconds.",
            "Sing a pop song chorus until you win (Make it convincing).",
            "Do a 360 spin.",
            "Sing the alphabet backwards.",
            "Speak only in haikus until you win.",
            "Randomly clap.",
            "Change game language (Give it 100%).",
            "Spin in chair 3 times until you win.",
            "Play with one eye closed.",
            "Play with one eye closed for 5 minutes.",
            "Speak like Shakespeare until you win.",
            "Compliment opponents for 1 minute.",
            "Randomly clap for 5 minutes.",
            "Act in love with the enemy for 30 seconds.",
            "Call yourself 'The Legend' (Be dramatic).",
            "Bark like a dog when you see an enemy for 10 minutes.",
            "Say 'Skill issue' for the next round.",
            "Play with one eye closed (No cheating!).",
            "Spin in chair 3 times for 5 minutes.",
            "Speak like Shakespeare (No cheating!).",
            "Randomly clap for 2 minutes.",
            "Narrate like a nature documentary for 30 seconds.",
            "Do a 360 spin for 2 minutes.",
            "Randomly clap for 3 minutes.",
            "Act in love with the enemy.",
            "Call yourself 'The Legend' for 10 minutes.",
            "Sing a pop song chorus for 10 minutes.",
            "Let chat decide sensitivity for 5 minutes.",
            "Bark like a dog when you see an enemy for 5 minutes (No cheating!).",
            "Let chat decide sensitivity for 30 seconds.",
            "Meow every time you reload for 5 minutes.",
            "Speak like Shakespeare for the next round (No cheating!).",
            "Yell 'Parkour!' for 1 minute.",
            "Pretend you're lagging for 3 minutes.",
            "Change game language (Chat watches closely).",
            "Pretend you're lagging for the next round.",
            "Sing a pop song chorus (Make it convincing).",
            "Call yourself 'The Legend' for the next round.",
            "Act in love with the enemy for the next round.",
            "Sing a pop song chorus (Give it 100%).",
            "Yell 'Parkour!' for 10 minutes.",
            "Compliment opponents for 3 minutes (Be dramatic).",
            "Call yourself 'The Legend'.",
            "Meow every time you reload.",
            "Spin in chair 3 times (Make it convincing).",
            "Change game language for 10 minutes.",
            "Let chat decide sensitivity until you win.",
            "Change game language."
        ]
    },
    {
        title: "Pack 5 - Impossible",
        color: "bg-blue",
        dares: [
            "Use weakest weapon for 5 minutes.",
            "Let chat pick your challenge until you die.",
            "Mousepad backwards for 1 round (Chat watches closely).",
            "Hands crossed for 5 minutes.",
            "No armor/shields for 1 round.",
            "Play blindfolded.",
            "No sprinting for 5 minutes.",
            "Mousepad backwards for 5 minutes (Be dramatic).",
            "No armor/shields.",
            "No armor/shields for 5 minutes.",
            "Pretend you're racing until you die.",
            "Close eyes during firefight for 5 minutes.",
            "Play with your keyboard upside down.",
            "Mousepad backwards for 1 round (Give it 100%).",
            "Do a wall sit for 5 minutes.",
            "Only walk backwards for 5 minutes (No cheating!).",
            "Only crouch-walk until you die.",
            "Do a dramatic victory speech.",
            "Close eyes during firefight (Give it 100%).",
            "Let chat dictate movement.",
            "Play with your keyboard upside down for 1 round.",
            "Close eyes during firefight for 1 round (No cheating!).",
            "Mousepad backwards (Be dramatic).",
            "Close eyes during firefight for 1 round.",
            "Only walk backwards (Give it 100%).",
            "No sprinting until you die (Be dramatic).",
            "Let chat dictate movement (No cheating!).",
            "Let chat pick your challenge for 1 round (Chat watches closely).",
            "Survive without attacking.",
            "No looking at minimap.",
            "Don't reload manually for 5 minutes (Give it 100%).",
            "Survive without attacking for 1 round.",
            "Don't reload manually.",
            "Do a 2-minute plank.",
            "Let chat command when to shoot for 5 minutes (Give it 100%).",
            "No looking at minimap (Make it convincing).",
            "Play with your keyboard upside down for 5 minutes.",
            "Only walk backwards (Be dramatic).",
            "Minimum screen brightness until you die.",
            "Let chat command when to shoot.",
            "No sprinting until you die (Make it convincing).",
            "Close eyes during firefight.",
            "Survive without attacking for 5 minutes.",
            "No sprinting.",
            "Pretend you're racing for 1 round (Be dramatic).",
            "Let chat command when to shoot until you die.",
            "No armor/shields (Make it convincing).",
            "Do a dramatic victory speech until you die.",
            "Play with no HUD.",
            "Do a wall sit for 1 round (Chat watches closely).",
            "Use weakest weapon (Be dramatic).",
            "Finish a game without jumping for 5 minutes.",
            "Play with no HUD for 1 round.",
            "Only walk backwards (Make it convincing).",
            "Do a 2-minute plank for 5 minutes.",
            "Hands crossed for 1 round.",
            "No looking at minimap (No cheating!).",
            "No armor/shields until you die.",
            "Let chat pick your challenge (Make it convincing).",
            "Close eyes during firefight until you die.",
            "Use weakest weapon for 5 minutes (Give it 100%).",
            "Do a wall sit until you die.",
            "Do a dramatic victory speech for 1 round.",
            "No sprinting until you die.",
            "Only walk backwards for 5 minutes.",
            "Let chat command when to shoot (Make it convincing).",
            "Let chat pick your challenge.",
            "Do a wall sit.",
            "Only crouch-walk for 5 minutes.",
            "Finish a game without jumping.",
            "Play with no HUD for 1 round (Give it 100%).",
            "Unbind reload key until you die.",
            "Play blindfolded (Be dramatic).",
            "Unbind reload key for 1 round.",
            "Do a 2-minute plank for 1 round.",
            "No looking at minimap for 1 round.",
            "Hands crossed (Give it 100%).",
            "Only crouch-walk.",
            "Let chat pick your challenge for 1 round.",
            "Pretend you're racing (Be dramatic).",
            "Play blindfolded for 5 minutes.",
            "Do a 2-minute plank for 1 round (Be dramatic).",
            "Play blindfolded for 1 round.",
            "Minimum screen brightness for 1 round.",
            "No sprinting for 1 round (No cheating!).",
            "Minimum screen brightness (Be dramatic).",
            "Don't reload manually until you die (Give it 100%).",
            "Mousepad backwards for 5 minutes.",
            "Mousepad backwards for 5 minutes (Make it convincing).",
            "Let chat dictate movement for 1 round.",
            "Don't reload manually until you die.",
            "Use weakest weapon.",
            "Mousepad backwards.",
            "Finish a game without jumping for 1 round.",
            "Mousepad backwards for 1 round (Be dramatic).",
            "Only use melee until you die.",
            "Only use melee.",
            "Minimum screen brightness.",
            "Only crouch-walk for 5 minutes (No cheating!).",
            "Let chat pick your challenge for 5 minutes."
        ]
    }
];

const friendsDares = [
    {
        title: "Easy",
        color: "bg-green",
        dares: [
            "Fake British accent.",
            "Hop on one foot.",
            "Act like you are swimming for 2 minutes.",
            "Play an invisible guitar (No cheating!).",
            "Lick your elbow.",
            "Make an ugly face.",
            "High five everyone (Chat watches closely).",
            "Hop on one foot for 30 seconds.",
            "Speak without moving lips.",
            "Sing Happy Birthday.",
            "Speak in rhyme.",
            "Fake British accent for 30 seconds.",
            "Hold a staring contest for 30 seconds (Give it 100%).",
            "Do a celebrity impression (Chat watches closely).",
            "Pretend to ride a horse.",
            "Make an ugly face for 1 minute (Be dramatic).",
            "Baby crying impression for 2 minutes.",
            "Play an invisible guitar.",
            "Hold a staring contest for 1 minute.",
            "Pretend to be a news reporter for 1 minute (Make it convincing).",
            "Compliment everyone for 1 minute.",
            "Baby crying impression (Chat watches closely).",
            "Laugh like a villain for 1 minute.",
            "Speak in rhyme for 1 minute (Give it 100%).",
            "Pretend you are a statue for 1 minute.",
            "Tell your funniest childhood story (No cheating!).",
            "Play an invisible guitar for 1 minute.",
            "Compliment everyone (Be dramatic).",
            "Fake British accent (Be dramatic).",
            "Talk like a robot for 2 minutes.",
            "Talk like a robot.",
            "Hold a staring contest.",
            "Read a text message.",
            "Dance.",
            "Read a text message (Chat watches closely).",
            "Hop on one foot (Chat watches closely).",
            "Make an ugly face for 1 minute.",
            "Speak without moving lips for 1 minute.",
            "Laugh like a villain for 2 minutes.",
            "Compliment everyone for 30 seconds.",
            "High five everyone.",
            "Dance for 2 minutes.",
            "Laugh like a villain (Chat watches closely).",
            "Compliment everyone for 30 seconds (No cheating!).",
            "Do a celebrity impression for 2 minutes.",
            "Read a text message (Make it convincing).",
            "High five everyone for 2 minutes.",
            "Juggle 3 objects.",
            "Do a celebrity impression for 2 minutes (Make it convincing).",
            "Pretend to ride a horse for 30 seconds.",
            "Tell your funniest childhood story.",
            "Hop on one foot for 1 minute (Chat watches closely).",
            "Do a cartwheel.",
            "Dance for 1 minute (No cheating!).",
            "Walk like a model.",
            "Laugh like a villain.",
            "Speak without moving lips for 2 minutes.",
            "Baby crying impression (No cheating!).",
            "Read a text message for 30 seconds (Chat watches closely).",
            "Hop on one foot for 1 minute.",
            "Baby crying impression.",
            "Read a text message (Give it 100%).",
            "Hop on one foot for 2 minutes (Be dramatic).",
            "Speak without moving lips for 30 seconds.",
            "Pretend you are a statue for 2 minutes.",
            "Read a text message for 2 minutes.",
            "Pretend to ride a horse for 1 minute.",
            "Juggle 3 objects for 2 minutes.",
            "Do a cartwheel (Be dramatic).",
            "Hold a staring contest for 30 seconds.",
            "Speak in rhyme for 30 seconds.",
            "Pretend to be a news reporter for 2 minutes.",
            "Pretend you are a statue.",
            "Pretend to be a news reporter.",
            "Make an ugly face for 30 seconds.",
            "Act like you are swimming for 30 seconds.",
            "Do a cartwheel for 30 seconds.",
            "Laugh like a villain for 30 seconds.",
            "Walk like a model (Make it convincing).",
            "Do a celebrity impression for 30 seconds (Be dramatic).",
            "Lick your elbow for 30 seconds.",
            "Sing Happy Birthday for 1 minute.",
            "Pretend you are a statue for 2 minutes (Give it 100%).",
            "Play an invisible guitar for 30 seconds.",
            "Laugh like a villain (No cheating!).",
            "Juggle 3 objects (Give it 100%).",
            "Lick your elbow for 2 minutes.",
            "Act like you are swimming.",
            "Do a celebrity impression.",
            "Tell your funniest childhood story for 2 minutes.",
            "Compliment everyone.",
            "Sing Happy Birthday for 2 minutes (Chat watches closely).",
            "Play an invisible guitar (Make it convincing).",
            "Walk like a model for 1 minute (Give it 100%).",
            "Hop on one foot (Give it 100%).",
            "Speak in rhyme for 2 minutes.",
            "Walk like a model (Chat watches closely).",
            "Make an ugly face (Make it convincing).",
            "Sing Happy Birthday for 30 seconds.",
            "Fake British accent for 2 minutes."
        ]
    },
    {
        title: "Medium",
        color: "bg-blue",
        dares: [
            "Sing a scary nursery rhyme for 3 rounds.",
            "Do 10 burpees for 1 minute.",
            "Act like a chicken for 1 minute.",
            "Talk with tongue sticking out for 1 minute.",
            "Balance a spoon on your nose.",
            "Swap seats for 1 minute.",
            "Draw a mustache for 2 minutes.",
            "Let someone write your status (Make it convincing).",
            "Let someone restyle your hair for 1 minute.",
            "Copy the person next to you for 3 rounds.",
            "Tell a joke.",
            "Animal impression.",
            "Do a movie scene for 2 minutes.",
            "Speak only in questions for 2 minutes.",
            "High-pitched voice.",
            "Freeze (Be dramatic).",
            "Touch your toes for 1 minute.",
            "Sing everything you say.",
            "Freeze for 2 minutes (Chat watches closely).",
            "Touch your toes (Chat watches closely).",
            "Made-up language.",
            "Copy the person next to you for 1 minute (Make it convincing).",
            "Tell a joke for 2 minutes.",
            "Balance a spoon on your nose for 1 minute.",
            "Let someone write your status for 2 minutes (Chat watches closely).",
            "Made-up language for 3 rounds.",
            "Let someone write your status for 1 minute (Give it 100%).",
            "Fashion model walk.",
            "Fashion model walk for 3 rounds.",
            "Talk with tongue sticking out.",
            "Do 10 burpees.",
            "Made-up language (Be dramatic).",
            "Sing everything you say for 3 rounds.",
            "Speak only in questions (Be dramatic).",
            "Do 10 burpees (Give it 100%).",
            "Act like a chicken.",
            "Let someone restyle your hair.",
            "Draw a mustache (No cheating!).",
            "Fashion model walk for 1 minute.",
            "Swap seats (No cheating!).",
            "Let someone restyle your hair for 2 minutes.",
            "Let someone write your status for 3 rounds.",
            "Balance a spoon on your nose for 2 minutes (Chat watches closely).",
            "Get a funny nickname for 3 rounds.",
            "Do a movie scene for 1 minute.",
            "Touch your toes for 2 minutes.",
            "Freeze for 1 minute (No cheating!).",
            "Freeze.",
            "Get a funny nickname for 2 minutes.",
            "Do a movie scene.",
            "Draw a mustache for 3 rounds.",
            "Let someone style your hair.",
            "Copy the person next to you.",
            "Let someone write your status.",
            "Sing a scary nursery rhyme for 1 minute.",
            "Pretend the floor is lava for 1 minute.",
            "Balance a spoon on your nose for 3 rounds.",
            "Sing everything you say (Be dramatic).",
            "Animal impression for 1 minute (Be dramatic).",
            "Freeze for 3 rounds.",
            "High-pitched voice (Be dramatic).",
            "Speak only in questions.",
            "High-pitched voice for 2 minutes.",
            "Swap seats for 3 rounds.",
            "Let someone style your hair (Give it 100%).",
            "Let someone style your hair for 3 rounds.",
            "Let someone write your status for 3 rounds (Make it convincing).",
            "Touch your toes.",
            "Balance a book on your head.",
            "Balance a book on your head (Chat watches closely).",
            "Touch your toes (No cheating!).",
            "Let someone write your status for 2 minutes.",
            "Speak only in questions for 1 minute (Make it convincing).",
            "Animal impression (Be dramatic).",
            "Copy the person next to you for 2 minutes.",
            "Do a movie scene for 1 minute (Chat watches closely).",
            "Freeze for 1 minute.",
            "Swap seats for 2 minutes.",
            "Pretend the floor is lava for 3 rounds.",
            "Fashion model walk for 1 minute (Be dramatic).",
            "Sing a scary nursery rhyme.",
            "Let someone write your status for 1 minute.",
            "Balance a book on your head for 3 rounds (Give it 100%).",
            "Get a funny nickname.",
            "Balance a book on your head (Be dramatic).",
            "Freeze for 2 minutes.",
            "Pretend the floor is lava.",
            "Touch your toes for 1 minute (Chat watches closely).",
            "Balance a book on your head for 2 minutes.",
            "Animal impression for 2 minutes (Be dramatic).",
            "Copy the person next to you (Chat watches closely).",
            "Let someone style your hair (No cheating!).",
            "Sing everything you say for 2 minutes.",
            "Speak only in questions (Make it convincing).",
            "Balance a book on your head for 1 minute.",
            "Get a funny nickname (Be dramatic).",
            "Let someone write your status for 1 minute (Be dramatic).",
            "Draw a mustache.",
            "Act like a monkey.",
            "Speak only in questions for 1 minute."
        ]
    },
    {
        title: "Hard",
        color: "bg-yellow",
        dares: [
            "Wear socks on hands for 1 minute.",
            "Drink a mixed concoction.",
            "Eat a spoon of ketchup until next turn.",
            "Wear socks on hands.",
            "Eat a raw onion slice until next turn (Make it convincing).",
            "Draw on your arm.",
            "Do 15 pushups (No cheating!).",
            "Post a prank status for 1 minute.",
            "Let the group tickle you until next turn (Chat watches closely).",
            "Call a random contact.",
            "Act out a movie silently.",
            "Walk backwards until next turn (Give it 100%).",
            "Post a prank status.",
            "Speak only in whispers until next turn.",
            "Pretend you're invisible until next turn.",
            "Do 30 jumping jacks until next turn.",
            "Wear socks on hands until next turn.",
            "Let everyone rename you until next turn.",
            "Eat a spoon of ketchup.",
            "Alien language (Be dramatic).",
            "Pretend to be an alien.",
            "Narrate others (Make it convincing).",
            "Eat a raw onion slice.",
            "Pretend to be an alien for 3 rounds (Chat watches closely).",
            "Alien language for 1 minute.",
            "Eat plain bread fast until next turn.",
            "Act out a movie silently for 1 minute.",
            "Wear socks on hands (Make it convincing).",
            "Eat a spoon of ketchup for 3 rounds.",
            "Mimic another player for 3 rounds.",
            "Pretend to be an alien for 3 rounds (Give it 100%).",
            "Let everyone rename you for 3 rounds.",
            "Clothes inside out for 1 minute.",
            "Let the group tickle you for 1 minute.",
            "Eat plain bread fast for 1 minute.",
            "Eat plain bread fast until next turn (Make it convincing).",
            "Do 15 pushups for 3 rounds.",
            "Walk backwards until next turn.",
            "Do 30 jumping jacks.",
            "Do 15 pushups (Make it convincing).",
            "Post a prank status for 3 rounds.",
            "Let the group tickle you for 3 rounds.",
            "Do 20 squats for 3 rounds.",
            "Do 20 squats (Make it convincing).",
            "Eat plain bread fast for 3 rounds (Give it 100%).",
            "Clothes inside out (Give it 100%).",
            "Call a random contact for 3 rounds.",
            "Act like a cat.",
            "Alien language.",
            "Speak only in whispers.",
            "Eat a spoon of ketchup for 1 minute (Chat watches closely).",
            "Eat a spoon of ketchup for 1 minute (No cheating!).",
            "Speak only in whispers for 3 rounds.",
            "Walk backwards for 3 rounds (Make it convincing).",
            "Narrate others until next turn.",
            "Drink a mixed concoction until next turn.",
            "Hold an ice cube until next turn.",
            "Act out a movie silently until next turn (No cheating!).",
            "Eat a spoon of ketchup (Be dramatic).",
            "Let someone draw on your face with lipstick for 3 rounds (Chat watches closely).",
            "Narrate others for 1 minute.",
            "Do 15 pushups.",
            "Eat plain bread fast (Give it 100%).",
            "Walk backwards.",
            "Hold an ice cube for 1 minute.",
            "Eat a raw onion slice for 3 rounds.",
            "Alien language (No cheating!).",
            "Let someone draw on your face with lipstick for 1 minute (Chat watches closely).",
            "Speak only in whispers for 1 minute (No cheating!).",
            "Do 15 pushups for 1 minute.",
            "Eat plain bread fast.",
            "Pretend to be an alien (Chat watches closely).",
            "Do 30 jumping jacks (Make it convincing).",
            "Act out a movie silently (Be dramatic).",
            "Pretend to be an alien until next turn.",
            "Speak only in whispers (Give it 100%).",
            "Act out a movie silently for 3 rounds.",
            "Eat plain bread fast for 1 minute (Be dramatic).",
            "Post a prank status for 1 minute (Make it convincing).",
            "Alien language until next turn.",
            "Mimic another player.",
            "Mimic another player until next turn.",
            "Do 20 squats.",
            "Let everyone rename you.",
            "Alien language for 3 rounds.",
            "Narrate others.",
            "Do 20 squats for 1 minute.",
            "Let everyone rename you for 1 minute.",
            "Pretend you're invisible.",
            "Pretend to be an alien for 3 rounds.",
            "Draw on your arm until next turn.",
            "Do 30 jumping jacks for 1 minute.",
            "Clothes inside out until next turn.",
            "Eat a raw onion slice for 1 minute (Chat watches closely).",
            "Clothes inside out.",
            "Let someone draw on your face with lipstick for 3 rounds.",
            "Hold an ice cube for 3 rounds.",
            "Let everyone rename you until next turn (Be dramatic).",
            "Let someone draw on your face with lipstick.",
            "Hold an ice cube."
        ]
    },
    {
        title: "Chaos",
        color: "bg-green",
        dares: [
            "Terrible superhero for the rest of the game (Chat watches closely).",
            "Walk like a crab for the rest of the game.",
            "Act like a zombie for 5 rounds.",
            "Act freezing cold.",
            "Walk like a crab for the rest of the game (Be dramatic).",
            "Sing everything.",
            "Fake cry for 1 minute.",
            "Movie quotes only (Give it 100%).",
            "Banned word for 5 rounds.",
            "Movie quotes only (Chat watches closely).",
            "Switch socks for the rest of the game (Give it 100%).",
            "Speak like a pirate.",
            "Pretend to be a dog.",
            "Movie quotes only.",
            "Act like a zombie (No cheating!).",
            "Swap shirts for the rest of the game (Make it convincing).",
            "Speak like a pirate for the rest of the game.",
            "Embarrassing story (Give it 100%).",
            "Fake cry for 5 rounds (Be dramatic).",
            "Speak like a pirate for the rest of the game (Be dramatic).",
            "Movie quotes only for the rest of the game (No cheating!).",
            "Third person.",
            "Terrible superhero for 1 minute (No cheating!).",
            "Laugh without stopping (Be dramatic).",
            "Pretend to be a dog (Chat watches closely).",
            "Laugh without stopping.",
            "Walk like a crab for 1 minute.",
            "Swap shirts for 1 minute.",
            "Act freezing cold for the rest of the game.",
            "Movie quotes only (No cheating!).",
            "Interpretive dance (Chat watches closely).",
            "Wear sunglasses indoors for the rest of the game.",
            "Dance with no music for the rest of the game.",
            "Terrible superhero for the rest of the game.",
            "Drink safe kitchen liquids (Be dramatic).",
            "Walk like a crab for 5 rounds.",
            "Switch socks for 1 minute.",
            "Speak like a pirate (Give it 100%).",
            "Walk like a penguin for 5 rounds (Chat watches closely).",
            "Third person for 1 minute (Make it convincing).",
            "Act out a meme.",
            "Wear sunglasses indoors for 5 rounds.",
            "Swap shirts for 5 rounds.",
            "Angry customer.",
            "Third person for 1 minute.",
            "Fake cry.",
            "Speak like a pirate for 1 minute.",
            "Blindfolded feeding for 1 minute.",
            "Interpretive dance for the rest of the game.",
            "Blindfolded feeding for 5 rounds.",
            "Fake cry for 5 rounds.",
            "Dance with no music for 5 rounds.",
            "Embarrassing alarm sound.",
            "Embarrassing story for 5 rounds (Be dramatic).",
            "Drink safe kitchen liquids.",
            "Act like a zombie for 1 minute.",
            "Drink safe kitchen liquids (Give it 100%).",
            "Swap shirts (Be dramatic).",
            "Switch socks for 5 rounds.",
            "Angry customer for 5 rounds (Give it 100%).",
            "Walk like a crab for 5 rounds (Chat watches closely).",
            "Banned word.",
            "Terrible superhero for 5 rounds.",
            "Angry customer for 5 rounds (Be dramatic).",
            "Switch socks for the rest of the game.",
            "Act like a zombie for the rest of the game.",
            "Terrible superhero for 1 minute.",
            "Act out a meme (No cheating!).",
            "Blindfolded feeding.",
            "Terrible superhero.",
            "Swap shirts.",
            "Laugh without stopping for 1 minute (Be dramatic).",
            "Act out a meme for 5 rounds.",
            "Dance with no music.",
            "Act out a meme for the rest of the game.",
            "Angry customer for 5 rounds.",
            "Wear sunglasses indoors.",
            "Swap shirts for the rest of the game.",
            "Walk like a penguin for the rest of the game (Give it 100%).",
            "Evil laugh for the rest of the game.",
            "Pretend to be a dog for the rest of the game.",
            "Swap shirts (No cheating!).",
            "Pretend to be a dog for 5 rounds.",
            "Walk like a penguin for 1 minute.",
            "Interpretive dance.",
            "Evil laugh.",
            "Walk like a crab.",
            "Switch socks.",
            "Act like a zombie.",
            "Walk like a penguin.",
            "Dance with no music (No cheating!).",
            "Laugh without stopping for 1 minute (Give it 100%).",
            "Sing everything (Be dramatic).",
            "Movie quotes only for 5 rounds.",
            "Angry customer for the rest of the game.",
            "Embarrassing alarm sound for the rest of the game.",
            "Evil laugh for the rest of the game (Give it 100%).",
            "Speak like a pirate for 5 rounds (Give it 100%).",
            "Fake cry for the rest of the game.",
            "Embarrassing story."
        ]
    },
    {
        title: "Extreme",
        color: "bg-blue",
        dares: [
            "Winner assigns dare (Be dramatic).",
            "Harmless tweet (No cheating!).",
            "Spoonful of hot sauce.",
            "Bite raw lemon (Make it convincing).",
            "Emoji from your phone (Chat watches closely).",
            "Bite raw lemon.",
            "Post silly photo until the game ends (Be dramatic).",
            "Winner assigns dare for 2 rounds.",
            "Draw unibrow.",
            "Silly selfie.",
            "Eat blindfolded for 2 rounds.",
            "Give phone away.",
            "Emoji from your phone.",
            "Funny pose.",
            "Emoji from your phone (No cheating!).",
            "Post silly photo for 2 rounds (No cheating!).",
            "Winner assigns dare.",
            "Toilet paper mummy (Chat watches closely).",
            "Imitate laughs (No cheating!).",
            "Crazy hairstyle until the game ends.",
            "Crazy hairstyle until the game ends (Give it 100%).",
            "Group chooses wallpaper for 2 rounds.",
            "Post silly photo until the game ends.",
            "Confusing text message until the game ends.",
            "Group chooses wallpaper for 2 rounds (Chat watches closely).",
            "Harmless tweet for 2 rounds (Give it 100%).",
            "Harmless tweet.",
            "Spoonful of mustard.",
            "Imitate laughs for 1 minute (Be dramatic).",
            "Confusing text message.",
            "Wear blindfold until the game ends (Make it convincing).",
            "Hold plank.",
            "Funny selfie to friend until the game ends (No cheating!).",
            "Eat blindfolded for 2 rounds (Chat watches closely).",
            "Post silly photo until the game ends (No cheating!).",
            "Song lyrics only.",
            "Silly selfie for 2 rounds.",
            "Emoji from your phone for 1 minute.",
            "Draw unibrow (Chat watches closely).",
            "Toilet paper mummy for 1 minute (Make it convincing).",
            "Wear blindfold (No cheating!).",
            "Wear blindfold.",
            "Raw garlic (Make it convincing).",
            "Winner assigns dare (Chat watches closely).",
            "Funny selfie to friend for 2 rounds (Be dramatic).",
            "Silly selfie for 1 minute.",
            "Crazy hairstyle.",
            "Raw garlic until the game ends (Give it 100%).",
            "Imitate laughs (Be dramatic).",
            "Group chooses wallpaper.",
            "Wear blindfold for 1 minute.",
            "Hold plank until the game ends.",
            "Toilet paper mummy until the game ends.",
            "Imitate laughs.",
            "Emoji from your phone for 1 minute (Chat watches closely).",
            "Eat blindfolded.",
            "Wear blindfold for 2 rounds.",
            "Crazy hairstyle for 1 minute.",
            "Victory speech for loser until the game ends.",
            "Spoonful of mustard (No cheating!).",
            "Give phone away until the game ends (Chat watches closely).",
            "Song lyrics only for 2 rounds.",
            "Funny selfie to friend for 1 minute.",
            "Imitate laughs (Give it 100%).",
            "Toilet paper mummy.",
            "Give phone away for 1 minute.",
            "Give phone away until the game ends.",
            "Raw garlic.",
            "Spoonful of hot sauce for 2 rounds.",
            "Imitate laughs for 2 rounds (Make it convincing).",
            "Draw unibrow until the game ends.",
            "Post silly photo for 1 minute.",
            "Hold plank for 1 minute.",
            "Funny accessory for 2 rounds.",
            "Funny accessory until the game ends.",
            "Funny accessory.",
            "Group chooses wallpaper until the game ends.",
            "Winner assigns dare until the game ends (Make it convincing).",
            "Raw garlic for 2 rounds.",
            "Emoji from your phone until the game ends.",
            "Drink salt water for 2 rounds (Be dramatic).",
            "Eat blindfolded until the game ends.",
            "Drink salt water for 1 minute.",
            "Funny selfie to friend.",
            "Funny selfie to friend (Chat watches closely).",
            "Funny selfie to friend until the game ends.",
            "Confusing text message for 1 minute.",
            "Victory speech for loser for 2 rounds.",
            "Raw garlic (Give it 100%).",
            "Raw garlic for 1 minute.",
            "Eat blindfolded for 2 rounds (Make it convincing).",
            "Draw unibrow (No cheating!).",
            "Funny selfie to friend for 1 minute (Make it convincing).",
            "Post silly photo.",
            "Spoonful of hot sauce (Be dramatic).",
            "Winner assigns dare for 1 minute.",
            "Wear blindfold until the game ends.",
            "Bite raw lemon until the game ends.",
            "Toilet paper mummy for 1 minute.",
            "Funny selfie to friend for 2 rounds."
        ]
    }
];

const privacyPolicy = `
    <h3>1. Introduction</h3>
    <p>Welcome to Dare Stacks! We create fun, interactive party games designed for friends and live streamers worldwide. Your privacy matters to us, which is why we have kept our privacy policy short, simple, and completely transparent. By using our website and interacting with our gameplay loops, you agree to the terms outlined below.</p>
    
    <h3>2. Information We Collect (Or Don't!)</h3>
    <p>No User Accounts: We do not require you to create an account, log in, or provide any personal data like your name, email address, or phone number to play Dare Stacks.</p>
    <p>Gameplay Data: All pack selections and dare completions happen locally in your web browser session. We do not track, store, or save your individual dare results on external permanent servers.</p>
    <p>Cookies & Local Storage: We use minor local browser storage solely to keep track of your active session (like remembering if you are on Dare 3 out of 10) so your game functions smoothly if you refresh or navigate the site.</p>
    
    <h3>3. Third-Party Advertisements & Global Data Transfers</h3>
    <p>To keep Dare Stacks 100% free for everyone, we display horizontal leaderboard advertisements at the base of our layout. These third-party ad networks (such as Google AdSense) may use cookies or basic non-personal device identifiers to serve relevant ads based on your general web browsing habits. Because this website is accessible worldwide, these third-party ad networks may process non-personal data across global servers. They do not have access to any personal data from our site, as we do not collect any.</p>
    
    <h3>4. International Privacy Rights (GDPR, CCPA, & DPDP)</h3>
    <p>EU/UK Users (GDPR): Since we do not collect personal data, we do not engage in the tracking, processing, or profiling of European citizens.</p>
    <p>US Users (CCPA/CPRA): We do not sell, rent, or share your personal information with third parties, because we do not collect any personal information to begin with.</p>
    <p>Indian Users (DPDP Act): We process all local session data based entirely on your voluntary consent to interact with our gameplay layout.</p>
    
    <h3>5. Children's Privacy</h3>
    <p>Dare Stacks is intended for a general audience. Because we do not collect, store, or share any personal identifiable information from any user, our platform is fully compliant with standard international digital privacy regulations (including COPPA and GDPR frameworks).</p>
    
    <h3>6. Future Support & Community</h3>
    <p>Dare Packs is currently in its vibrant, initial launch phase! We are entirely focused on perfecting our endless pack rollers and delivering the ultimate dare experience for you and your friends. Because we are a lean indie creator building this in real-time, our dedicated contact portal and community channels are currently under construction. We will be launching full player support and feedback systems in the coming months. Until then, deal your cards, challenge your friends, and stay tuned for major updates!</p>
`;
